member_hobbies={
        '松田':{'sns','麻雀','自転車'},
        '浅木':{'麻雀','食べ歩き','数学','数学','数学'}
}
#全員の趣味一覧表示
print(member_hobbies)
#松田の趣味一覧表示
print(member_hobbies['松田'])
#浅木の趣味一覧表示
print(member_hobbies['浅木'])
